# Generated by Django 4.2.3 on 2023-07-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
